Redact PII for logs and metrics
cashapp/cash-app-pay-android-sdk pull request #112
Opened 2023-06-29 23:22 UTC by pedronveloso

2023-06-30 17:21 UTC, cpetzel requested changes
So we still need to give the client the CashTag via our callbacks, so they can display it... But we should be sure to redact that information in our analytic events, and be sure that we are not logging it in LogCat or any other system output. (we also need to add a note in our documentation and also our API KDocs that there is PII in this data class).

2023-06-30 20:02 UTC, pedronveloso commented
> So we still need to give the client the CashTag via our callbacks, so they can display it... But we should be sure to redact that information in our analytic events, and be sure that we are not logging it in LogCat or any other system output. (we also need to add a note in our documentation and also our API KDocs that there is PII in this data class).

Client's can have access to the info by using this well documented function:

```
/**
   * Returns the un-redacted value of this PiiString. Do not log or store this value!
   */
  fun getUnredacted(): String {
    return value
  }
  ```

2023-07-02 18:36 UTC, cpetzel commented
> > So we still need to give the client the CashTag via our callbacks, so they can display it... But we should be sure to redact that information in our analytic events, and be sure that we are not logging it in LogCat or any other system output. (we also need to add a note in our documentation and also our API KDocs that there is PII in this data class).
> 
> Client's can have access to the info by using this well documented function:
> 
> ```
> /**
>    * Returns the un-redacted value of this PiiString. Do not log or store this value!
>    */
>   fun getUnredacted(): String {
>     return value
>   }
> ```

I am of the opinion that we should give the clients the raw data, and its up to them to treat it safely, rather then give them restricted info, and make them dive into the class structure to grab what they want.

This is what PayKit web does (with the only thing they redact, which is the redirectUrl). 

We should also mimic paykit web and redact (some) of the redirect url.

2023-07-05 23:50 UTC, cpetzel commented on core/src/main/java/app/cash/paykit/core/network/adapters/PiiStringAdapter.kt
> +internal class PiiStringAdapter : JsonAdapter<PiiString>() {
Can we add some kdoc here to denote that this class parses it as a string... but when it writes to JSON, it will redact the value?

2023-07-06 00:02 UTC, cpetzel commented on core/src/main/java/app/cash/paykit/core/models/pii/PiiString.kt
> +  }
This seems like an internal concern only... Could we just remove this function and hardcode our redacted value in the adapter?

2023-07-06 17:14 UTC, pedronveloso commented on core/src/main/java/app/cash/paykit/core/models/pii/PiiString.kt
> +  }
Makes sense

2023-07-06 17:15 UTC, pedronveloso commented on core/src/main/java/app/cash/paykit/core/network/adapters/PiiStringAdapter.kt
> +internal class PiiStringAdapter : JsonAdapter<PiiString>() {
Sure

2023-07-06 22:46 UTC, pedronveloso commented
Most recent commit verification: 


![Screenshot_20230706_152928](https://github.com/cashapp/cash-app-pay-android-sdk/assets/416941/b8c1373c-68d3-4f5e-a1d4-f2b6035908d2)

![Screenshot_20230706_153020](https://github.com/cashapp/cash-app-pay-android-sdk/assets/416941/c0125e30-e23e-4fb6-bd10-bbb4b40b53a5)

2023-07-06 23:14 UTC, cpetzel commented
This is nice and clean! 

Are there DevApp changes to this? 

How/Why is the cashtag greyed out in this screenshot?
<img width="477" alt="image" src="https://github.com/cashapp/cash-app-pay-android-sdk/assets/2036206/6a2d8777-d0f3-4a99-99c0-06e548b9730a">

2023-07-07 00:14 UTC, pedronveloso commented
> This is nice and clean!
> 
> Are there DevApp changes to this?
> 
> How/Why is the cashtag greyed out in this screenshot? <img alt="image" width="477" src="https://user-images.githubusercontent.com/2036206/251595124-6a2d8777-d0f3-4a99-99c0-06e548b9730a.png">

Yes, they'll be in the respective repo.

2023-07-07 00:14 UTC, merged